version: '3.8' # It's recommended to use a more recent Docker Compose version

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8078:80" # Maps host port 8078 to container port 80
    container_name: olx-price-tracker-web
    volumes:
      - ./src:/var/www/html:delegated # Mounts your application source code to the container
      - ./docker/config/php.ini:/usr/local/etc/php/php.ini # Mounts a custom PHP configuration file
      - ./docker/config/apache2.conf:/etc/apache2/apache2.conf # Mounts a custom Apache configuration file
      - ./docker/config/envvars:/etc/apache2/envvars # Mounts Apache environment variables
      - ~/.composer/docker-cache/:/root/.composer:cached # Caches Composer dependencies for faster builds
    depends_on:
      - mysql_db # Ensures the database container starts before the web container
    networks:
      - olx_price_tracker
    # For better debugging if the container crashes immediately, you can uncomment these:
    # stdin_open: true
    # tty: true

  mysql_db:
    image: mysql:8.0
    restart: always # Ensures the database container automatically restarts if it stops
    container_name: olx-price-tracker-db
    volumes:
      - ./mysql_db:/var/lib/mysql # Persists MySQL database data to a host volume
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: olx_price_tracker
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_0900_ai_ci',
        '--wait_timeout=28800',
        '--default-authentication-plugin=mysql_native_password'
      ]
    networks:
      - olx_price_tracker

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql_db # Links phpMyAdmin to the MySQL database service for easy connection
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 300000M
      MEMORY_LIMIT: 300000M
      MAX_EXECUTION_TIME: 300000
    ports:
      - "8048:80" # Maps host port 8048 to container port 80 for the phpMyAdmin UI
    container_name: olx-price-tracker-phpmyadmin
    networks:
      - olx_price_tracker

networks:
  olx_price_tracker:
  # driver: bridge # This explicitly defines the network driver as bridge (optional, as it's the default)